os: windows

dist: 1803-containers

language: bash

group: dev

before_install:
  - env | sort
  - curl https://sh.rustup.rs -sSf | sh -s -- -y
  - git clone https://github.com/servo/rust-url
  - cd rust-url
  - git submodule update --init --recursive
  - cargo build
  - cargo test --verbose

