os: windows

dist: 1803-containers

language: bash

group: dev

before_install:
  - env | sort
  - cd $HOME
  - curl -sL -o gimme https://raw.githubusercontent.com/travis-ci/gimme/master/gimme
  - chmod +x gimme
  - uname -s
  - export GIMME_OS=windows
  - ./gimme -h
  - gimme --known
  - ./gimme stable
  - go -v
