os: windows

dist: 1803-containers

language: bash

group: dev

before_install:
  - env | sort
  - cd $HOME
  - mkdir -p ~/.bin
  - curl -sL -o ./bin/gimme https://raw.githubusercontent.com/travis-ci/gimme/master/gimme
  - chmod +x .bin/gimme
  - export PATH="$HOME/.bin:${PATH}"
  - uname -s
  - export GIMME_OS=windows
  - gimme -h
  # - ./gimme --known
  - eval "$(gimme stable)"
  - go -v
