os: windows

language: node_js

group: dev

node_js:
  - 6
  - 8
  - 10

#cache:
#  branch: ha-file-null
#  directories:
#  - "$HOME/.tmp-cache/node_modules"

before_install:
  - env | sort
  - choco list --local-only
  - cd $HOME
  - git clone https://github.com/yargs/yargs
  - cd yargs
  - mkdir -p node_modules
