os: windows

dist: 1803-containers

language: go

group: dev

go:
- stable

env:
- GIMME_OS=windows

before_install:
  - env | sort
  - cd $HOME
  - mkdir -p ~/.bin
  - export 
  - gimme -h
  # - ./gimme --known
  - eval "$(gimme stable)"
  - go version
