os: windows

language: bash

before_install:
  - git clone git://github.com/phpenv/phpenv.git ~/.phpenv
  - export PATH="$HOME/.phpenv/bin:$PATH"
  - eval "$(phpenv init -)"
  - git clone https://github.com/php-build/php-build $(phpenv root)/plugins/php-build
  - phpenv install 7.2
  - phpenv rehash

script: echo "nearly"
