os: windows

language: bash

before_install:
  - env
  - ls "%TEMP%"
  - choco.exe config list
  - choco.exe install php --version 7.2.0
  - "PATH=%ChocolateyToolsLocation%\php;%PATH%"
  - env
  #- refreshenv.exe
  #- php.exe -v
  #- php.exe -i
  - ls 'C:\tools\'
  - ls 'C:\tools\php72\'
  - "%ChocolateyToolsLocation%\php72\php.exe -v"
  - "%ChocolateyToolsLocation%\php72\php.exe -i"
  # - choco.exe install composer
  #- refreshenv.exe
  #- composer.exe --version

script: echo "nearly"
