os: windows

language: bash

group: dev

env:
  - NODE_VERSION=6
  - NODE_VERSION=8
  - NODE_VERSION=10

cache:
  directories:
  - "$HOME/.npm"

before_install:
  - echo "--------------------------------------"
  - env | sort
  - echo "--------------------------------------"
  - choco list --local-only
  - echo "--------------------------------------"
  - export NVS_HOME=$ProgramData/nvs
  - git clone --single-branch -b joshk-msys_nt https://github.com/joshk/nvs $NVS_HOME
  - . $NVS_HOME/nvs.sh
  - echo "--------------------------------------"
  - env | sort
  - echo "--------------------------------------"
  - nvs add $NODE_VERSION
  - nvs use $NODE_VERSION
  - echo "--------------------------------------"
  - node --version
  - npm --version
  - echo "--------------------------------------"
  - cd ~
  - git clone https://github.com/yargs/yargs
  - cd yargs
  - echo "--------------------------------------"
  - npm ci
  - npm t
